# Generated by Django 4.0.4 on 2022-04-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='teach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teach', to='lessons.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
