# Generated by Django 4.0.4 on 2022-04-28 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0003_language_teach_alter_language_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Оставьте отзыв о преподавателе', max_length=500)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_teacher', to='lessons.teacher')),
            ],
            options={
                'verbose_name_plural': 'Отзыв',
            },
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
